version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    docker:
      - image: 'cimg/node:current'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run Tests
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
