version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:latest
    steps:
      - checkout
      - run: npm run lint
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
